version: '3'

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: app
    hostname: app
    ports:
      - "8081:8081"

  mongo:
    image: mongo:latest
    hostname: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    command: [--auth]
    networks:
      - my-network

  mongo-seed:
    build: ./data
    networks:
      - my-network
    depends_on:
      - mongo

networks:
  my-network:
    driver: bridge